Public Class BlodGivning
    Private Sub BlodGivning_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        ComboBox1.Items.Add("Ja")
        ComboBox1.Items.Add("Nei")

        listboxEgenerklæring.Items.Add("Vennligst besvar:")
        listboxEgenerklæring.Items.Add("- Har du fått informasjon om blodgivning?")
        listboxEgenerklæring.Items.Add("- Føler du deg frisk nå?")
        listboxEgenerklæring.Items.Add("- Hvis du har gitt blod tidligere, har du vært frisk i perioden fra forrige blodgivning og til nå?")
        listboxEgenerklæring.Items.Add("- Veier du 50 kg eller mer?")
        listboxEgenerklæring.Items.Add("- Har du åpne sår, eksem eller hudsykdom?")
        listboxEgenerklæring.Items.Add("- Har du piercing i slimhinne?")
        listboxEgenerklæring.Items.Add("- Har du i løpet av de siste fire uker:")
        listboxEgenerklæring.Items.Add("- brukt medisiner?")
        listboxEgenerklæring.Items.Add("- vært syk eller hatt feber?")
        listboxEgenerklæring.Items.Add("- hatt løs avføring?")
        listboxEgenerklæring.Items.Add("- fått vaksine?")
        listboxEgenerklæring.Items.Add("- vært hos tannlege eller tannpleier?")
        listboxEgenerklæring.Items.Add("Har du i løpet av de siste seks måneder:")
        listboxEgenerklæring.Items.Add("- vært til legeundersøkelse eller på sykehus, eller fått behandling for noen sykdom?")
        listboxEgenerklæring.Items.Add("- fått behandling med sprøyter?")
        listboxEgenerklæring.Items.Add("- hatt kjønnssykdom, eller fått behandling for kjønnssykdom?")
        listboxEgenerklæring.Items.Add("- hatt seksuell kontakt med person med HIVinfeksjon eller hepatitt B eller hepatitt C,")
        listboxEgenerklæring.Items.Add(" eller med person som har hatt positiv test for en av disse sykdommene?")
        listboxEgenerklæring.Items.Add("- hatt seksuell kontakt med person som bruker eller har brukt dopingmidler eller narkotiske midler som sprøyter?")
        listboxEgenerklæring.Items.Add("- hatt seksuell kontakt med prostituerte eller tidligere prostituerte?")
        listboxEgenerklæring.Items.Add("- blitt tatovert, fått piercing eller tatt hull i ørene?")
        listboxEgenerklæring.Items.Add("- fått akupunktur?")
        listboxEgenerklæring.Items.Add("- stukket eller skåret deg på gjenstander som var forurenset med blod eller kroppsvæsker")
        listboxEgenerklæring.Items.Add("- bodd i samme husstand som en person som har hepatitt B?")
        listboxEgenerklæring.Items.Add("- fått blodsøl på slimhinner eller skadet hud?")
        listboxEgenerklæring.Items.Add("- blitt bitt av flått?")
        listboxEgenerklæring.Items.Add("- hatt seksualpartner som har bodd mer enn ett år sammenhengende utenfor Vest-Europa ?")
        listboxEgenerklæring.Items.Add("- hatt seksualpartner som har vært i Afrika?")
        listboxEgenerklæring.Items.Add("- hatt seksuell kontakt med en person som har fått blod eller blodprodukter utenfor Norden?")
        listboxEgenerklæring.Items.Add("- hatt ny seksualpartner?")
        listboxEgenerklæring.Items.Add("- vært utenfor Vest-Europa?")
        listboxEgenerklæring.Items.Add("Har du i løpet av de siste to år:")
        listboxEgenerklæring.Items.Add("- hatt sjeldne eller alvorlige infeksjonssykdommer?")
        listboxEgenerklæring.Items.Add("Har du på noe tidspunkt gjennom livet")
        listboxEgenerklæring.Items.Add("- hatt, hjerte-, lever-, eller lungesykdom?")
        listboxEgenerklæring.Items.Add("- hatt kreft?")
        listboxEgenerklæring.Items.Add("- hatt blødningstendens?")
        listboxEgenerklæring.Items.Add("- hatt allergi mot mat eller medisiner?")
        listboxEgenerklæring.Items.Add("- hatt malaria?")
        listboxEgenerklæring.Items.Add("- hatt tropesykdommer?")
        listboxEgenerklæring.Items.Add("- hatt hepatitt (gulsott), HIV-infeksjon eller AIDS?")
        listboxEgenerklæring.Items.Add("- hatt positiv prøve for hepatitt (gulsott) eller HIVinfeksjon?")
        listboxEgenerklæring.Items.Add("- fått blodoverføring?")
        listboxEgenerklæring.Items.Add("- fått veksthormon?")
        listboxEgenerklæring.Items.Add("- fått hornhinnetransplantat?")
        listboxEgenerklæring.Items.Add("- hatt syfilis?")
        listboxEgenerklæring.Items.Add("- hatt alvorlig sykdom som ikke er nevnt her?")
        listboxEgenerklæring.Items.Add("- brukt dopingmidler eller narkotiske midler som sprøyter?")
        listboxEgenerklæring.Items.Add("- mottatt penger eller narkotika som gjenytelse for sex?")
        listboxEgenerklæring.Items.Add("Besvares av kvinner:")
        listboxEgenerklæring.Items.Add("- Er du gravid?")
        listboxEgenerklæring.Items.Add("- Har du vært gravid i løpet av de siste tolv måneder, eller ammer du nå?")
        listboxEgenerklæring.Items.Add("- Hvis du har gitt blod tidligere, har du vært gravid siden forrige blodgivning?")
        listboxEgenerklæring.Items.Add("- Har du i løpet av de siste seks måneder hatt seksuell kontakt med en mann som du vet har hatt seksuell kontakt med andre menn?")
        listboxEgenerklæring.Items.Add("Besvares av menn:")
        listboxEgenerklæring.Items.Add("- Har eller har du hatt seksuell kontakt med andre menn?")
        listboxEgenerklæring.Items.Add("Besvar også:")
        listboxEgenerklæring.Items.Add("- Har du brukt narkotika en eller flere ganger de siste 12 måneder?")
        listboxEgenerklæring.Items.Add("- Har du eller noen i familien hatt Creutzfeldt-Jakob sykdom eller variant CJD?")
        listboxEgenerklæring.Items.Add("- Har du oppholdt deg i Storbritannia i mer enn ett år til sammen i perioden mellom 1980 og 1996?")
        listboxEgenerklæring.Items.Add("- Har du i løpet av de siste tre år vært i områder der malaria forekommer?")
        listboxEgenerklæring.Items.Add("- Har du oppholdt deg sammenhengende i minst seks måneder i områder der malaria forekommer?")
        listboxEgenerklæring.Items.Add("- Har du oppholdt deg i Afrika i mer enn fem år til sammen?")
        listboxEgenerklæring.Items.Add("- Er du eller din mor født i Amerika sør for USA?")
        listboxEgenerklæring.Items.Add("- Godtar du at anonymiserte prøver av ditt blod kan brukes til forskning?")
        listboxEgenerklæring.Items.Add("- Har du deltatt i medikamentforsøk de siste 12 måneder?")
        listboxEgenerklæring.Items.Add("- Jeg samtykker i at mitt plasma føres ut av Norge for legemiddelproduksjon.")
        listboxEgenerklæring.Items.Add("- I hvilke(t) land er du født og oppvokst?")
    End Sub

    Private Sub btnNeste_Click(sender As Object, e As EventArgs) Handles btnNeste.Click
        If ComboBox1.Text = "Nei" Then
            Ansatt.Show()
            Me.Hide()
        Else
            BlodGivning2.Show()
            Me.Hide()
        End If
    End Sub
End Class